name: Release

on:
  push:
    branches:
      - master
      - github-workflows

jobs:
  test:
    name: Test
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: [8.x, 10.x]
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Setup node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache and restore modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ matrix.node-version }}-npm-${{ hashFiles('package-lock.json') }}
          restore-keys: ${{ runner.os }}-${{ matrix.node-version }}-npm-
      - name: Install packages
        run: npm install
      - name: Run test
        run: npm test
  build_release:
    name: Build Release
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: [10.x]
    needs: test
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Setup node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache and restore modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ matrix.node-version }}-npm-${{ hashFiles('package-lock.json') }}
          restore-keys: ${{ runner.os }}-${{ matrix.node-version }}-npm-
      - name: Install packages
        run: npm install
      - name: Run semantic-release
        run: npm run semantic-release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
